version: "3.9"

services:
  app:
    build: .
    container_name: my_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
      NODE_ENV: production
    depends_on:
      - db
    command: npm start

  db:
    image: postgres:16-alpine
    container_name: my_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
